spring.application.name=spring-circuitbreaker
server.port=9003
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Circuit breaker
resilience4j.circuitbreaker.instances.getWeatherCircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.getWeatherCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.getWeatherCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.getWeatherCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.getWeatherCircuitBreaker.wait-duration-in-openState=5s
resilience4j.circuitbreaker.instances.getWeatherCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.getWeatherCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.getWeatherCircuitBreaker.sliding-window-type=COUNT_BASED

#Retry 2 times each after 5sec delay
resilience4j.retry.instances.getWeatherCircuitBreaker.register-health-indicator=true
resilience4j.retry.instances.getWeatherCircuitBreaker.max-retry-attempts=2
resilience4j.retry.instances.getWeatherCircuitBreaker.wait-duration=5s


#Rate limiter: limits 10 requests for duration of 10sec (usually in milisec in PROD) after it wait for 3sec.
ratelimiter.instances.getWeatherCircuitBreaker.register-health-indicator=true
ratelimiter.instances.getWeatherCircuitBreaker.limit-for-period=10
ratelimiter.instances.getWeatherCircuitBreaker.limit-refresh-period=10s
ratelimiter.instances.getWeatherCircuitBreaker.timeout-duration=3s